server:
  port: 8888
  error:
    whitelabel:
      enabled: false
spring:
  profiles:
    active:
      - local
      - jdbc
      - monitor
      - query
  sleuth:
    sampler:
      probability: 1.0
#  zipkin:
#    base-url: http://localhost:9411/
#    sender:
#      type: web
  application:
    name: centralize-configuration
  datasource:
    hikari:
      max-lifetime: 900000
      connection-timeout: 50000
      pool-name: ${spring.application.name}-local-pool
      minimum-idle: 1
    url: jdbc:mysql://127.0.0.1:3306/centralize_configuration?useUnicode=yes&characterEncoding=UTF-8
    username: daniel
    password: P@s$w0rd123!
  jpa:
    open-in-view: false
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        generate_statistics: false
        jdbc:
          batch_size: 50
    show-sql: false
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yml
    enabled: true
    contexts: local
    default-schema: centralize_configuration
    liquibase-schema: centralize_configuration
    parameters:
      ds: "$"
      process-id-log: "${ds}{PID}"
      liquibase-context: local
  mvc:
    throw-exception-if-no-handler-found: true
  cloud:
    config:
      server:
        jdbc:
          sql: SELECT  `key`,value  FROM centralize_configuration.configuration where application =? and profile =? and label = ?
          order: 1
        default-label: 'default'
        default-profile: 'default'
        git:
          uri: https://github.com/daniel18082021/acm-lcincom-irs-centralize-configuration.git
          username: daniel18082021
          password: Vung@oi!mora123
    bus:
      enabled: true
    stream:
      kafka:
        binder:
          brokers:
            - localhost:29092
  kafka:
    properties:
      security:
        protocol: PLAINTEXT
  web:
    resources:
      add-mappings: false
logging:
  level:
    "net.ttddyy.dsproxy" : trace
  pattern:
    level: "${spring.application.name}|%X{X-B3-TraceId:-},%X{X-B3-SpanId:-},%X{X-Span-Export:-},%X{CorrelationId}"
    console: "%d{yyyy-MM-dd'T'HH:mm:ss.SXXX}|2|%level|${logging.pattern.level}|${PID}|%thread|%logger{40}|%message%n"
management:
  endpoints:
    web:
      exposure:
        include: metrics, prometheus, health, info,refresh, bus-refresh
      base-path: /
  server:
    port: 18443
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
    health:
      enabled: true
    info:
      enabled: true
    refresh:
      enabled: true
    bus-refresh:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
application:
  numberRecordPerPage: 50
